### ISSUE TITLE
Group sorting incorrect

### ISSUE THREAD

**Issue by AlexGabourie** [AlexGabourie/thermo#2]
Sorting by group in gpumd.io.ase_atoms_to_gpumd is not working perfectly, though it is not too bad. There is a slight order issue. Not a critical issue, but should be fixed.

**Comment by brucefan1983** [comment]
GPUMD does not require the group indices to be ordered. It only requires
the type indices to be ordered in some way for multi-potential simulations.
If there two or more grouping methods, there may be no way to make both
odered. So what is the grouping issue here?

AlexG <notifications@github.com> 于 2019年3月12日周二 06:54写道：

**Comment by AlexGabourie** [comment]
This isn't an issue that would break GPUMD at all. I just added group ordering because it has helped me check that my structures are indeed correct by visually separating groups in the xyz.in files. Certainly not a critical issue, but my code does not work exactly like my documentation states.
